name: "Pytest"

on:
  push:
    branches: [ main ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-20.04
    environment: TestEnv
    permissions:
      actions: read
      contents: read
      security-events: read

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Make secret.txt
      env:
        TEST_SECRET: ${{ secrets.TEST_SECRET }}
      run: echo $TEST_SECRET > test/secret.txt
    
    - name: Run tests with pytest
      run: cd test && cat secret.txt && pytest -v -k 'not test_fail'
